// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20200727203318_Test5")]
    partial class Test5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.CourseManagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CourseManagementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigmentID")
                        .HasColumnType("int")
                        .HasMaxLength(20);

                    b.Property<string>("AssignmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("CourseManagements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c769e19d-c895-4ad0-97dc-9b497bff0d3e"),
                            AssigmentID = 0,
                            AssignmentTitle = "GitHub Tutorial.",
                            Description = "Learn the basic of GitHub."
                        },
                        new
                        {
                            Id = new Guid("c47748fb-1fa7-4745-a863-78fa91633c93"),
                            AssigmentID = 0,
                            AssignmentTitle = "Calculator",
                            Description = "Build a calculator using the basic math."
                        },
                        new
                        {
                            Id = new Guid("a12001ac-75cd-43ad-916f-79e1a8cd40f1"),
                            AssigmentID = 0,
                            AssignmentTitle = "Statistic Application",
                            Description = "Build an app that includes basic math and statistics."
                        });
                });

            modelBuilder.Entity("Entities.Models.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CourseSectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseSection");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b172b1b-f32d-4dfd-be2f-0a6c56bc2447"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(3716),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(3256),
                            SectionID = "D01",
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(2756),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(4158),
                            UserId = "80abbca8-664d-4b20-b5de-024705497d4a"
                        },
                        new
                        {
                            Id = new Guid("7d31f5e1-bfb4-4e35-983d-d33269299e04"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5094),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5087),
                            SectionID = "D02",
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5066),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5103),
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479813"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5122),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5120),
                            SectionID = "D03",
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5118),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(5124),
                            UserId = ""
                        });
                });

            modelBuilder.Entity("Entities.Models.Courses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b172b1b-f32d-4dfd-be2f-0a6c56bc2446"),
                            CourseName = "Web Systems Development",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(6796),
                            Description = "Learn version control and apply the concepts to building an API using Python, Docker, and Pycharm. ",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(7263)
                        },
                        new
                        {
                            Id = new Guid("7d31f5e1-bfb4-4e35-983d-d33269299e03"),
                            CourseName = "	Web Services and Middleware",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(7741),
                            Description = "Learn how to build an ASP .NET Web using C# and github.",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(7773)
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            CourseName = "	Enterprise Database Management",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(7794),
                            Description = "Students will obtain a conceptual foundation of database design and explore the implications for organizational database usage.",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(7796)
                        });
                });

            modelBuilder.Entity("Entities.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            OrgName = "xyz org"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            OrgName = "lmnop org"
                        });
                });

            modelBuilder.Entity("Entities.Models.SectionAssign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SectionAssignID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsersID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectionAssigns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fb597ea-72aa-4ddf-8d06-f009ad8a2d3a"),
                            AssignID = "C769E19D-C895-4AD0-97DC-9B497BFF0D3E",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(6770),
                            Score = 91,
                            SubmissionText = "Please see link to assignment.",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(7269),
                            UsersID = "80abbca8-664d-4b20-b5de-024705497d4a"
                        },
                        new
                        {
                            Id = new Guid("a884663b-f3c7-46da-a541-9cef2ff12d66"),
                            AssignID = "C769E19D-C895-4AD0-97DC-9B497BFF0D3E",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(8556),
                            Score = 84,
                            SubmissionText = "Please see link to assignment.",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(8575),
                            UsersID = "021ca3c1-0deb-4afd-ae94-2159a8479811"
                        },
                        new
                        {
                            Id = new Guid("df38bdf1-c93b-43e6-9ed1-0da79d774967"),
                            AssignID = "C769E19D-C895-4AD0-97DC-9B497BFF0D3E",
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(8609),
                            Score = 99,
                            SubmissionText = "Please see link to assignment.",
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(8611),
                            UsersID = "86dba8c0-d178-41e7-938c-ed49778fb52a"
                        });
                });

            modelBuilder.Entity("Entities.Models.SectionEnrollManage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SectionEnrollID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SectionEnrollManages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f6e887a-40f1-4032-a347-5c526d7ca36d"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(264),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(9817),
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 681, DateTimeKind.Local).AddTicks(9323),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(697)
                        },
                        new
                        {
                            Id = new Guid("b880cf73-b029-4c6d-ae21-6ee0a7a8e243"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1176),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1169),
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1153),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1185)
                        },
                        new
                        {
                            Id = new Guid("a6a002f5-7d7b-4a3c-977b-cd78f55252bf"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1212),
                            EndDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1211),
                            StartDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1208),
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 682, DateTimeKind.Local).AddTicks(1214)
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SectionEnrollManageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemRoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSectionId");

                    b.HasIndex("CoursesId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SectionEnrollManageId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            CourseID = new Guid("6b172b1b-f32d-4dfd-be2f-0a6c56bc2446"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 679, DateTimeKind.Local).AddTicks(9631),
                            Email = "sderosa@njit.edu",
                            OrganizationId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Password = "pass123",
                            Status = "Active",
                            SystemRoleID = 2000001,
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(306),
                            UserName = "sderosa",
                            age = 34
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            CourseID = new Guid("7d31f5e1-bfb4-4e35-983d-d33269299e03"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(1713),
                            Email = "zwaltz@njit.edu",
                            OrganizationId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Password = "hippo87",
                            Status = "Active",
                            SystemRoleID = 3000008,
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(1739),
                            UserName = "zwaltz",
                            age = 24
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            CourseID = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            CreatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(1769),
                            Email = "stussel@njit.edu",
                            OrganizationId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Password = "newyork1",
                            Status = "Active",
                            SystemRoleID = 8000007,
                            UpdatedDate = new DateTime(2020, 7, 27, 16, 33, 17, 680, DateTimeKind.Local).AddTicks(1771),
                            UserName = "stussel",
                            age = 48
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "c33786ac-5d83-40e9-a8e9-5b6aa943ce4b",
                            ConcurrencyStamp = "3eefaae4-5b09-450f-81bd-0d730e65f721",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "a55c4876-0364-49c2-9b60-aa06554d46d7",
                            ConcurrencyStamp = "2bdf9824-8f4d-4770-a7a7-de2f9e92f8de",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3813142f-681f-45ca-a7ad-6cfc5f6ce068",
                            ConcurrencyStamp = "3c34ba59-e625-42b6-acaa-9145ee18e913",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.Models.CourseSection", null)
                        .WithMany("Users")
                        .HasForeignKey("CourseSectionId");

                    b.HasOne("Entities.Models.Courses", "Courses")
                        .WithMany()
                        .HasForeignKey("CoursesId");

                    b.HasOne("Entities.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.SectionEnrollManage", null)
                        .WithMany("Users")
                        .HasForeignKey("SectionEnrollManageId");
                });
#pragma warning restore 612, 618
        }
    }
}
